name: Setup
description: Setup Python version and install dependencies

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: make install
      shell: bash
      