name: robot-ci
on:
  pull_request: null
  push:
    branches:
      - main
  workflow_dispatch: null

jobs:
  robot_api_tests_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clean project
        run: make clean

      - name: Install dependencies
        run: make install

      - name: Run tests
        run: make run-test-report

      - name: Get allure report
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure report action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: ${{ github.workspace }}/logs/allure-reports

      - name: Deploy report to gh-pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ${{ github.workspace }}/logs/allure-reports