name: ROBOT-CI

on:
  pull_request: null
  push:
    branches:
      - main
  workflow_dispatch: null

jobs:
  robot_schema_tests:
    name: Run schema tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clean project
        run: make clean

      - name: Install dependencies
        run: make install

      - name: Run schema tests
        if: always()
        run: make run-all-schema
        continue-on-error: true

      - name: Upload allure report
        uses: actions/upload-artifact@v3

  generate_report:
    name: Generate report
    needs: [robot_schema_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Download allure report
        uses: actions/download-artifact@v3

      - name: Get allure history
        uses: actions/checkout@v2
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure report gh-actions
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          #gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to gh-pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history