name: robot-ci
on:
  pull_request: null
  push:
    branches:
      - main
  workflow_dispatch: null

jobs:
  robot_schema_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clean project
        run: make clean

      - name: Install dependencies
        run: make install

      - name: Run tests
        run: make run-all-schema

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: ./allure_results
          gh_pages: gh-pages
          allure_report: allure_report
          allure_history: allure_history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure_history

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with: 
            authToken: ${{secrets.TOKEN}}
            context: 'Test report'
            state: 'success'
            sha: ${{ github.event.pull_request.head.sha }}
            target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}