name: ROBOT-CI
on:
  pull_request: null
  push:
    branches:
      - main
  workflow_dispatch: null

jobs:
  robot_schema_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clean project
        run: make clean

      - name: Install dependencies
        run: make install

      - name: Run schema tests
        run: make run-all-schema

  generate_report:
    needs: [robot_schema_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Get allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure report gh-actions
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: ./allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to gh-pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        env:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
