name: robot-ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  robot_schema_tests:
    name: robot schema tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Start ServeRest locally
        run: docker run -d -p 3000:3000 paulogoncalvesbh/serverest

      - name: Run tests
        if: always()
        run: env=local make run-all-schema
        continue-on-error: true

      - name: Upload Allure report
        uses: actions/upload-artifact@v1
        with:
          name: allure-results
          path: allure-results
  
  robot_integration_tests:
    name: robot integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Start ServeRest locally
        run: docker run -d -p 3000:3000 paulogoncalvesbh/serverest

      - name: Run tests
        if: always()
        run: env=local make run-all-integration
        continue-on-error: true

      - name: Upload Allure report
        uses: actions/upload-artifact@v1
        with:
          name: allure-results
          path: allure-results

  generate_report:
    name: generate report
    needs: [robot_schema_tests, robot_integration_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Download Allure report
        uses: actions/download-artifact@v1
        with:
          name: allure-results

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure report gh-actions
        uses: simple-elf/allure-report-action@v1.6
        if: always()
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to gh-pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
          